name = "hur-ma"
compatibility_date = "2024-04-03"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".next"

[[d1_databases]]
binding = "DB"
database_name = "hur-ma-db"
database_id = "1b8a6ebc-769f-4dcb-aa48-c4d6715cd847"
migrations_dir = "prisma/migrations"
